let JSONOuput = {
    "permissionsInformation": {
        "hasInheritedLinks": false,
        "links": [{
            "isInherited": false,
            "linkDetails": {
                "AllowsAnonymousAccess": false,
                "ApplicationId": null,
                "BlocksDownload": false,
                "Created": "2020-11-03T07:49:04.928Z",
                "CreatedBy": {
                    "email": "user1@contoso.onmicrosoft.com",
                    "expiration": "",
                    "id": 6,
                    "isActive": true,
                    "isExternal": false,
                    "jobTitle": "CEO",
                    "loginName": "i:0#.f|membership|user1@contoso.onmicrosoft.com",
                    "name": "User 1",
                    "principalType": 0,
                    "userId": null,
                    "userPrincipalName": "user1@contoso.onmicrosoft.com"
                },
                "Description": null,
                "Embeddable": false,
                "Expiration": "",
                "HasExternalGuestInvitees": true,
                "Invitations": [{
                    "invitedBy": {
                        "email": "user1@contoso.onmicrosoft.com",
                        "expiration": "",
                        "id": 6,
                        "isActive": true,
                        "isExternal": false,
                        "jobTitle": "CEO",
                        "loginName": "i:0#.f|membership|user1@contoso.onmicrosoft.com",
                        "name": "User 1",
                        "principalType": 1,
                        "userId": null,
                        "userPrincipalName": "user1@contoso.onmicrosoft.com"
                    },
                    "invitedOn": "2020-11-03T07:49:04.803Z",
                    "invitee": {
                        "email": "user2@contoso.onmicrosoft.com",
                        "expiration": "",
                        "id": 17,
                        "isActive": true,
                        "isExternal": false,
                        "jobTitle": "CEO",
                        "loginName": "i:0#.f|membership|user2@contoso.onmicrosoft.com",
                        "name": "User 2",
                        "principalType": 1,
                        "userId": null,
                        "userPrincipalName": "user2@contoso.onmicrosoft.com"
                    }
                }, {
                    "invitedBy": {
                        "email": "user1@contoso.onmicrosoft.com",
                        "expiration": "",
                        "id": 6,
                        "isActive": true,
                        "isExternal": false,
                        "jobTitle": "CEO",
                        "loginName": "i:0#.f|membership|user1@contoso.onmicrosoft.com",
                        "name": "User 1",
                        "principalType": 1,
                        "userId": null,
                        "userPrincipalName": "user1@contoso.onmicrosoft.com"
                    },
                    "invitedOn": "2020-11-03T07:49:04.803Z",
                    "invitee": {
                        "email": "user3@contoso.onmicrosoft.com",
                        "expiration": "",
                        "id": 18,
                        "isActive": true,
                        "isExternal": false,
                        "jobTitle": "Executive Vice President",
                        "loginName": "i:0#.f|membership|user3@contoso.onmicrosoft.com",
                        "name": "User 3",
                        "principalType": 1,
                        "userId": null,
                        "userPrincipalName": "user3@contoso.onmicrosoft.com"
                    }
                }, {
                    "invitedBy": {
                        "email": "user1@contoso.onmicrosoft.com",
                        "expiration": "",
                        "id": 6,
                        "isActive": true,
                        "isExternal": false,
                        "jobTitle": "CEO",
                        "loginName": "i:0#.f|membership|user1@contoso.onmicrosoft.com",
                        "name": "User 1",
                        "principalType": 1,
                        "userId": null,
                        "userPrincipalName": "user1@contoso.onmicrosoft.com"
                    },
                    "invitedOn": "2020-11-03T07:49:04.803Z",
                    "invitee": {
                        "email": "external1@externalcontoso.onmicrosoft.com",
                        "expiration": "",
                        "id": 23,
                        "isActive": true,
                        "isExternal": true,
                        "jobTitle": null,
                        "loginName": "i:0#.f|membership|external1_externalcontoso#ext#@contoso.onmicrosoft.com",
                        "name": "External User 1",
                        "principalType": 1,
                        "userId": null,
                        "userPrincipalName": "external1_externalcontoso#ext#@contoso.onmicrosoft.com"
                    }
                }, {
                    "invitedBy": {
                        "email": "user1@contoso.onmicrosoft.com",
                        "expiration": "",
                        "id": 6,
                        "isActive": true,
                        "isExternal": false,
                        "jobTitle": "CEO",
                        "loginName": "i:0#.f|membership|user1@contoso.onmicrosoft.com",
                        "name": "User 1",
                        "principalType": 1,
                        "userId": null,
                        "userPrincipalName": "user1@contoso.onmicrosoft.com"
                    },
                    "invitedOn": "2020-11-05T11:10:20.239Z",
                    "invitee": {
                        "email": "user4@contoso.onmicrosoft.com",
                        "expiration": "",
                        "id": 20,
                        "isActive": true,
                        "isExternal": false,
                        "jobTitle": "Executive Vice President",
                        "loginName": "i:0#.f|membership|user4@contoso.onmicrosoft.com",
                        "name": "User 4",
                        "principalType": 1,
                        "userId": null,
                        "userPrincipalName": "user4@contoso.onmicrosoft.com"
                    }
                }],
                "IsActive": true,
                "IsAddressBarLink": false,
                "IsCreateOnlyLink": false,
                "IsDefault": true,
                "IsEditLink": false,
                "IsFormsLink": false,
                "IsReviewLink": false,
                "IsUnhealthy": false,
                "LastModified": "2020-11-05T12:11:05.914Z",
                "LastModifiedBy": {
                    "email": "user1@contoso.onmicrosoft.com",
                    "expiration": "",
                    "id": 6,
                    "isActive": true,
                    "isExternal": false,
                    "jobTitle": "CEO",
                    "loginName": "i:0#.f|membership|user1@contoso.onmicrosoft.com",
                    "name": "User 1",
                    "principalType": 0,
                    "userId": null,
                    "userPrincipalName": "user1@contoso.onmicrosoft.com"
                },
                "LimitUseToApplication": false,
                "LinkKind": 6,
                "PasswordLastModified": "",
                "PasswordLastModifiedBy": null,
                "RedeemedUsers": [],
                "RequiresPassword": false,
                "RestrictedShareMembership": true,
                "Scope": 2,
                "ShareId": "6205a23e-e1fb-49e0-ba6d-e4ae76638de3",
                "ShareTokenString": "share=EVv36NDX3I5HnKpBlE8h1yIBLsx9EUjgBSgEN0fnh-3tQA",
                "SharingLinkStatus": 0,
                "TrackLinkUsers": false,
                "Url": "https://contoso.sharepoint.com/:w:/s/project-x/EVv36NDX3I5HnKpBlE8h1yIBLsx9EUjgBSgEN0fnh-3tQA"
            },
            "linkMembers": [{
                "email": "external1@externalcontoso.onmicrosoft.com",
                "expiration": "",
                "id": 23,
                "isActive": true,
                "isExternal": true,
                "jobTitle": null,
                "loginName": "i:0#.f|membership|external1_externalcontoso#ext#@contoso.onmicrosoft.com",
                "name": "External User 1",
                "principalType": 1,
                "userId": null,
                "userPrincipalName": "external1_externalcontoso#ext#@contoso.onmicrosoft.com"
            }, {
                "email": "user2@contoso.onmicrosoft.com",
                "expiration": "",
                "id": 17,
                "isActive": true,
                "isExternal": false,
                "jobTitle": "CEO",
                "loginName": "i:0#.f|membership|user2@contoso.onmicrosoft.com",
                "name": "User 2",
                "principalType": 1,
                "userId": null,
                "userPrincipalName": "user2@contoso.onmicrosoft.com"
            }, {
                "email": "user4@contoso.onmicrosoft.com",
                "expiration": "",
                "id": 20,
                "isActive": true,
                "isExternal": false,
                "jobTitle": "Executive Vice President",
                "loginName": "i:0#.f|membership|user4@contoso.onmicrosoft.com",
                "name": "User 4",
                "principalType": 1,
                "userId": null,
                "userPrincipalName": "user4@contoso.onmicrosoft.com"
            }, {
                "email": "user3@contoso.onmicrosoft.com",
                "expiration": "",
                "id": 18,
                "isActive": true,
                "isExternal": false,
                "jobTitle": "Executive Vice President",
                "loginName": "i:0#.f|membership|user3@contoso.onmicrosoft.com",
                "name": "User 3",
                "principalType": 1,
                "userId": null,
                "userPrincipalName": "user3@contoso.onmicrosoft.com"
            }]
        }, {
            "isInherited": false,
            "linkDetails": {
                "AllowsAnonymousAccess": false,
                "ApplicationId": null,
                "BlocksDownload": false,
                "Created": "",
                "CreatedBy": null,
                "Description": null,
                "Embeddable": false,
                "Expiration": "",
                "HasExternalGuestInvitees": false,
                "Invitations": [],
                "IsActive": false,
                "IsAddressBarLink": false,
                "IsCreateOnlyLink": false,
                "IsDefault": true,
                "IsEditLink": false,
                "IsFormsLink": false,
                "IsReviewLink": false,
                "IsUnhealthy": false,
                "LastModified": "",
                "LastModifiedBy": null,
                "LimitUseToApplication": false,
                "LinkKind": 5,
                "PasswordLastModified": "",
                "PasswordLastModifiedBy": null,
                "RedeemedUsers": [],
                "RequiresPassword": false,
                "RestrictedShareMembership": false,
                "Scope": -1,
                "ShareId": "00000000-0000-0000-0000-000000000000",
                "ShareTokenString": null,
                "SharingLinkStatus": 0,
                "TrackLinkUsers": false,
                "Url": null
            },
            "linkMembers": []
        }, {
            "isInherited": false,
            "linkDetails": {
                "AllowsAnonymousAccess": false,
                "ApplicationId": null,
                "BlocksDownload": false,
                "Created": "",
                "CreatedBy": null,
                "Description": null,
                "Embeddable": false,
                "Expiration": "",
                "HasExternalGuestInvitees": false,
                "Invitations": [],
                "IsActive": false,
                "IsAddressBarLink": false,
                "IsCreateOnlyLink": false,
                "IsDefault": true,
                "IsEditLink": false,
                "IsFormsLink": false,
                "IsReviewLink": false,
                "IsUnhealthy": false,
                "LastModified": "",
                "LastModifiedBy": null,
                "LimitUseToApplication": false,
                "LinkKind": 4,
                "PasswordLastModified": "",
                "PasswordLastModifiedBy": null,
                "RedeemedUsers": [],
                "RequiresPassword": false,
                "RestrictedShareMembership": false,
                "Scope": -1,
                "ShareId": "00000000-0000-0000-0000-000000000000",
                "ShareTokenString": null,
                "SharingLinkStatus": 0,
                "TrackLinkUsers": false,
                "Url": null
            },
            "linkMembers": []
        }, {
            "isInherited": false,
            "linkDetails": {
                "AllowsAnonymousAccess": false,
                "ApplicationId": null,
                "BlocksDownload": false,
                "Created": "",
                "CreatedBy": null,
                "Description": null,
                "Embeddable": false,
                "Expiration": "",
                "HasExternalGuestInvitees": false,
                "Invitations": [],
                "IsActive": false,
                "IsAddressBarLink": false,
                "IsCreateOnlyLink": false,
                "IsDefault": true,
                "IsEditLink": false,
                "IsFormsLink": false,
                "IsReviewLink": false,
                "IsUnhealthy": false,
                "LastModified": "",
                "LastModifiedBy": null,
                "LimitUseToApplication": false,
                "LinkKind": 3,
                "PasswordLastModified": "",
                "PasswordLastModifiedBy": null,
                "RedeemedUsers": [],
                "RequiresPassword": false,
                "RestrictedShareMembership": false,
                "Scope": -1,
                "ShareId": "00000000-0000-0000-0000-000000000000",
                "ShareTokenString": null,
                "SharingLinkStatus": 0,
                "TrackLinkUsers": false,
                "Url": null
            },
            "linkMembers": []
        }, {
            "isInherited": false,
            "linkDetails": {
                "AllowsAnonymousAccess": false,
                "ApplicationId": null,
                "BlocksDownload": false,
                "Created": "",
                "CreatedBy": null,
                "Description": null,
                "Embeddable": false,
                "Expiration": "",
                "HasExternalGuestInvitees": false,
                "Invitations": [],
                "IsActive": false,
                "IsAddressBarLink": false,
                "IsCreateOnlyLink": false,
                "IsDefault": true,
                "IsEditLink": false,
                "IsFormsLink": false,
                "IsReviewLink": false,
                "IsUnhealthy": false,
                "LastModified": "",
                "LastModifiedBy": null,
                "LimitUseToApplication": false,
                "LinkKind": 2,
                "PasswordLastModified": "",
                "PasswordLastModifiedBy": null,
                "RedeemedUsers": [],
                "RequiresPassword": false,
                "RestrictedShareMembership": false,
                "Scope": -1,
                "ShareId": "00000000-0000-0000-0000-000000000000",
                "ShareTokenString": null,
                "SharingLinkStatus": 0,
                "TrackLinkUsers": false,
                "Url": null
            },
            "linkMembers": []
        }],
        "principals": [{
            "principal": {
                "email": "",
                "expiration": null,
                "id": 3,
                "isActive": true,
                "isExternal": false,
                "jobTitle": null,
                "loginName": "project-x Owners",
                "name": "project-x Owners",
                "principalType": 8,
                "userId": null,
                "userPrincipalName": null
            },
            "role": 3
        }, {
            "principal": {
                "email": "",
                "expiration": null,
                "id": 4,
                "isActive": true,
                "isExternal": false,
                "jobTitle": null,
                "loginName": "project-x Visitors",
                "name": "project-x Visitors",
                "principalType": 8,
                "userId": null,
                "userPrincipalName": null
            },
            "role": 1
        }, {
            "principal": {
                "email": "",
                "expiration": null,
                "id": 5,
                "isActive": true,
                "isExternal": false,
                "jobTitle": null,
                "loginName": "project-x Members",
                "name": "project-x Members",
                "principalType": 8,
                "userId": null,
                "userPrincipalName": null
            },
            "role": 2
        }],
        "siteAdmins": [{
            "principal": {
                "email": "user1@contoso.onmicrosoft.com",
                "expiration": "",
                "id": 6,
                "isActive": true,
                "isExternal": false,
                "jobTitle": "CEO",
                "loginName": "i:0#.f|membership|user1@contoso.onmicrosoft.com",
                "name": "User 1",
                "principalType": 1,
                "userId": null,
                "userPrincipalName": "user1@contoso.onmicrosoft.com"
            },
            "role": 3
        }]
    }
  };
  
  let textOutput = [
  {
    SharedWith: "User 2",
    IsActive: "true",
    IsExternal: "false",
    PrincipalType: "User"
  },
  {
    SharedWith: "User 3",
    IsActive: "true",
    IsExternal: "false",
    PrincipalType: "User"
  },
  {
    SharedWith: "External User 1",
    IsActive: "true",
    IsExternal: "true",
    PrincipalType: "User"
  },
  {
    SharedWith: "User 4",
    IsActive: "true",
    IsExternal: "false",
    PrincipalType: "User"
  },
  {
    SharedWith: "project-x Owners",
    IsActive: "true",
    IsExternal: "false",
    PrincipalType: "SharePointGroup"
  },
  {
    SharedWith: "project-x Visitors",
    IsActive: "true",
    IsExternal: "false",
    PrincipalType: "SharePointGroup"
  },
  {
    SharedWith: "project-x Members",
    IsActive: "true",
    IsExternal: "false",
    PrincipalType: "SharePointGroup"
  }  
  ];